"""Synthesizer — generates artifacts from evidence."""

from workpilot.contracts import MissionContract
from workpilot.evidence.store import EvidenceStore
from workpilot.providers.base import LLMProvider


class Synthesizer:
    """Generates artifacts based on contract and evidence.

    Phase 1: returns stub artifacts built directly from evidence.
    Phase 4+: will use LLM provider for real generation.
    """

    def __init__(self, provider: LLMProvider) -> None:
        self.provider = provider

    def generate(
        self,
        contract: MissionContract,
        evidence_store: EvidenceStore,
    ) -> dict[str, str | dict]:
        """Generate all artifacts. Returns {filename: content}.

        For Phase 1, builds deterministic artifacts from evidence store.
        """
        evidences = evidence_store.list_all()
        evidence_refs = [ev.evidence_id for ev in evidences]

        # weekly_report.md
        report_lines = [
            "## Summary\n",
            f"Goal: {contract.goal}\n",
            "\n## Progress\n",
        ]
        for ev in evidences:
            report_lines.append(f"- {ev.quote} [{ev.evidence_id}]\n")
        report_lines.append("\n## Decisions\n\n- No decisions recorded. [unknown]\n")
        report_lines.append("\n## Risks\n\n- See risks.json for structured risk list.\n")
        report_lines.append("\n## Next Week\n\n- See action_items.json for next steps.\n")
        weekly_report = "".join(report_lines)

        # risks.json
        risks = {
            "schema_version": "0.1",
            "risks": [
                {
                    "risk_id": "R-0001",
                    "title": "Stub risk — replace with real analysis",
                    "description": "This is a placeholder risk generated by StubProvider.",
                    "severity": "unknown",
                    "status": "unknown",
                    "source_refs": evidence_refs[:1] if evidence_refs else [],
                    "reason": "Phase 1 stub output.",
                }
            ],
        }

        # action_items.json
        action_items = {
            "schema_version": "0.1",
            "action_items": [
                {
                    "action_id": "A-0001",
                    "title": "Implement real synthesis with LLM provider",
                    "owner": None,
                    "owner_status": "unknown",
                    "due_date": None,
                    "due_date_status": "unknown",
                    "source_refs": evidence_refs[:1] if evidence_refs else [],
                    "reason": "Phase 1 stub output — real generation in Phase 4.",
                    "status": "proposed",
                }
            ],
        }

        return {
            "weekly_report.md": weekly_report,
            "risks.json": risks,
            "action_items.json": action_items,
        }
